name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  # Lint:
  # Lint任务
  UnitTest:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.2.1
      - name: Install modules
        run: pnpm install
      - name: Run Test
        run: pnpm run test
